import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { BarChart3, Download, Eye, Loader2, ShoppingBag, TrendingUp } from "lucide-react";

function MetricCard({ icon: Icon, label, today, week, suffix = "" }: { icon: typeof Eye; label: string; today: number; week: number; suffix?: string }) {
  return <article className="rounded-[22px] border border-[#e3d9ca] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#68747a]">{label}</span><span className="rounded-full bg-[#efe8dc] p-2 text-[#b9854a]"><Icon className="h-4 w-4" /></span></div><p className="mt-5 font-display text-3xl font-black text-[#173247]">{today}{suffix}</p><p className="mt-1 text-xs text-[#68747a]">اليوم · {week}{suffix} خلال آخر 7 أيام</p></article>;
}

export default function AdminAnalytics() {
  const query = trpc.admin.analyticsSummary.useQuery();
  const data = query.data;
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl space-y-6"><header className="rounded-[28px] bg-[#173247] p-6 text-white shadow-[0_20px_60px_rgba(23,50,71,0.16)] sm:p-8"><p className="text-xs font-bold tracking-[0.18em] text-[#d5a15f]">MIDAD / ANALYTICS</p><div className="mt-2 flex items-start justify-between gap-4"><div><h1 className="font-display text-3xl font-bold">الإحصائيات</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-white/70">ملخص تشغيلي مبني على الأحداث المسجلة فعلياً، دون تخزين محتوى شخصي ضمن سجل الزيارات.</p></div><BarChart3 className="hidden h-10 w-10 text-[#d5a15f] sm:block" /></div></header>{query.isLoading ? <div className="rounded-2xl bg-white p-10 text-center text-[#68747a]"><Loader2 className="mx-auto h-6 w-6 animate-spin" /></div> : query.isError ? <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm font-bold text-red-800">تعذر تحميل الإحصائيات حالياً.</div> : data ? <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard icon={Eye} label="الزوار الفريدون" today={data.todayVisitors} week={data.weekVisitors} /><MetricCard icon={Download} label="تحميلات العينات" today={data.todaySampleDownloads} week={data.weekSampleDownloads} /><MetricCard icon={ShoppingBag} label="طلبات الشراء" today={data.todayPurchaseRequests} week={data.weekPurchaseRequests} /><MetricCard icon={TrendingUp} label="معدل التحويل" today={data.todayConversionRate} week={data.weekConversionRate} suffix="%" /></div><section className="rounded-[24px] border border-[#e3d9ca] bg-white p-6 shadow-sm"><h2 className="font-display text-xl font-bold text-[#173247]">قراءة سريعة</h2><p className="mt-3 text-sm leading-7 text-[#68747a]">المعدل الحالي يُحتسب من طلبات الشراء مقارنة بتحميلات العينات. هذه إحصائية تشغيلية أولية وليست بديلاً عن أدوات تحليل متقدمة أو تقارير مالية.</p></section></> : null}</div></DashboardLayout>;
}
